name:                hbtc
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ProofOfKeags/hbtc
license:             UNLICENSE
author:              Keagan McClelland
maintainer:          keagan.mcclelland@gmail.com
copyright:           (c) 2018-2020 Keagan McClelland
category:            bitcoin
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - rio

library:
  source-dirs:      src
